# Generated by Django 4.2.1 on 2024-06-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('cep', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('pedido', models.CharField(max_length=100)),
            ],
        ),
    ]
