# Generated by Django 4.2.1 on 2024-06-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('auto', models.CharField(max_length=100)),
                ('preco', models.CharField(max_length=100)),
            ],
        ),
    ]
