# Generated by Django 4.2.1 on 2024-06-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoFornecedor',
            fields=[
                ('codfornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('datarecebimento', models.DateField()),
            ],
        ),
    ]
